/**
 * Dashboard-specific types: progress stats, AI recommendations, and aggregated dashboard data
 */

import type { CurrentStatus } from './current-status.types';
import type { TrainingPlan } from './training-plan.types';
import type { NutritionPlan } from './nutrition.types';
import type { PhysicalData, WeightProgressData } from './physical-data.types';
import type { WorkoutStats } from './workout-session.types';

export interface ProgressStats {
  _id: string;
  userId: string;
  last7Days: { weightDiff: number; fatDiff: number; workoutsCompleted: number };
  last30Days: { weightDiff: number; fatDiff: number; workoutsCompleted: number };
  autoGeneratedAt: string;
}

export interface AiRecommendation {
  _id: string;
  userId: string;
  category: 'training' | 'nutrition' | 'general';
  content: string;
  generatedBy: 'ai' | 'trainer';
  aiModelUsed?: string;
  metadata?: {
    prompt?: string;
    temperature?: number;
    tokensUsed?: number;
    version?: string;
    tags?: string[];
  };
  createdAt: string;
}

export interface DashboardData {
  currentStatus: CurrentStatus | null;
  activeTrainingPlan: TrainingPlan | null;
  activeNutritionPlan: NutritionPlan | null;
  trainingPlans: TrainingPlan[];
  nutritionPlans: NutritionPlan[];
  latestPhysicalData: PhysicalData | null;
  weightProgress: WeightProgressData | null;
  bmi: { bmi: number; category: string } | null;
  progressStats: ProgressStats | null;
  /** Streak, adherence and personal bests, derived from WorkoutSession. */
  workoutStats: WorkoutStats | null;
  aiRecommendations: AiRecommendation[];
}
